# Generated by Django 3.1.1 on 2020-10-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
