# Generated by Django 3.1.1 on 2020-10-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingprofile_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='updated',
        ),
    ]
